import { Brain, Layers, Paperclip, Terminal } from 'lucide-react'
import type { WorkspaceTab } from '../../store/workspace-view-store'

type Tab = Exclude<WorkspaceTab, 'code'>

const TAB_CONFIG: Record<Tab, { icon: React.ReactNode; description: string }> = {
  artifacts: {
    icon: <Layers size={32} className="text-fg-tertiary" strokeWidth={1.25} />,
    description: 'Structured plans and decisions generated by agents. Coming soon.'
  },
  context: {
    icon: <Paperclip size={32} className="text-fg-tertiary" strokeWidth={1.25} />,
    description: 'Drop files and notes for agents to reference. Coming soon.'
  },
  memory: {
    icon: <Brain size={32} className="text-fg-tertiary" strokeWidth={1.25} />,
    description: 'Patterns and decisions learned across workspaces. Coming soon.'
  },
  sessions: {
    icon: <Terminal size={32} className="text-fg-tertiary" strokeWidth={1.25} />,
    description: 'Agent session history for this workspace. Coming soon.'
  }
}

const TAB_LABELS: Record<Tab, string> = {
  artifacts: 'Artifacts',
  context:   'Context',
  memory:    'Memory',
  sessions:  'Sessions'
}

type Props = {
  tab: Tab
}

export function EmptyTabPage({ tab }: Props) {
  const { icon, description } = TAB_CONFIG[tab]

  return (
    <div className="flex-1 flex items-center justify-center p-8">
      <div className="flex flex-col items-center text-center max-w-xs">
        {icon}
        <h2 className="text-[16px] font-medium text-fg mt-3">{TAB_LABELS[tab]}</h2>
        <p className="text-[13px] text-fg-tertiary mt-2 leading-relaxed">{description}</p>
      </div>
    </div>
  )
}
