export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  PROJECT_NAME_TAKEN: 'PROJECT_NAME_TAKEN',
  WORKSPACE_NAME_TAKEN: 'WORKSPACE_NAME_TAKEN',
  BRANCH_NAME_TAKEN: 'BRANCH_NAME_TAKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_CONTRIBUTOR: 'ALREADY_CONTRIBUTOR',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
  ACCESS_DENIED: 'ACCESS_DENIED',
  ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',
  ARTIFACT_KIND_TAKEN: 'ARTIFACT_KIND_TAKEN',
  ARTIFACT_VERSION_CONFLICT: 'ARTIFACT_VERSION_CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
